services:
  - docker
  
before_install:
  - docker build -t slacknet/react-test -f ./client/Dockerfile.dev ./client
        
script:
  - docker run -e CI=true slacknet/react-test npm test

after_success:
  - docker build -t ukernel/multi-client ./client
  - docker build -t ukernel/multi-nginx ./nginx
  - docker build -t ukernel/multi-server ./server
  - docker build -t ukernel/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ukernel/multi-client
  - docker push ukernel/multi-nginx
  - docker push ukernel/multi-server
  - docker push ukernel/multi-worker

deploy:
  edge: true 
  provider: elasticbeanstalk 
  region: eu-central-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-eu-central-1-049588697487
  bucket_path: docker-multi
  on:
    branch: master 
# Access to AWS Beanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY