services:
  - docker
  
before_install:
  - docker build -t slacknet/react-test -f ./client/Dockerfile.dev ./client
        
script:
  - docker run -e CI=true slacknet/react-test npm test

after_success:
  - docker build -t slacknet/multi-client ./client
  - docker build -t slacknet/multi-nginx ./nginx
  - docker build -t slacknet/multi-server ./server
  - docker build -t slacknet/multi-worker ./worker
  # Login in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ukernel/multi-client
  - docker push ukernel/multi-nginx
  - docker push ukernel/multi-server
  - docker push ukernel/multi-worker